const port = '8000';

const express = require('express');
const session = require('express-session');
const bodyParser = require('body-parser');

const app = express();

const db = require('./src/modules/setup_database');

const path = require('path');
const fs = require('fs');

app.set('views', path.join(__dirname, 'src/views'));
app.set('view engine', 'pug');

// Formats the HTML generated by Pug neatly
app.locals.pretty = true;

// Allows us to access '/src/static' by using just '/static' in a browser
app.use('/static', express.static(path.join(__dirname, 'src/static')));

// Allows us to access '/src/modules' by using just '/modules' in a browser
app.use('/modules', express.static(path.join(__dirname, 'src/modules')));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.use(
    session({
        secret: 'mysecretkeygoeshere',
        resave: true,
        saveUninitialized: true
    })
);

const routes = require('./src/routes/routes')(app, fs);

app.listen(port, () => {
    console.log(`Listening to requests on http://localhost:${port}`);
});
